spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:/db/schema-h2.sql
    #    data: classpath:/db/data-h2.sql
    url: jdbc:h2:./h2/testdb
    username: sa
    password: sa
    platform: h2
    continue-on-error: true
  h2:
    # h2 web consloe ??????GUI????????????????h2 web consloe
    console:
      # ?? h2 web console ?????
      enabled: true
      # ???? url/h2-console ?? h2 web
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8888
#  flyway:
#   url: jdbc:h2:./h2/testdb
#   user: sa
#   password: sa
